const fs = require('fs');
const path = require('path');

function walkDir(dir, callback) {
  fs.readdirSync(dir).forEach(f => {
    let dirPath = path.join(dir, f);
    let isDirectory = fs.statSync(dirPath).isDirectory();
    isDirectory ? walkDir(dirPath, callback) : callback(dirPath);
  });
}

walkDir(path.join(__dirname, 'src'), (filePath) => {
  if (filePath.endsWith('.ts') || filePath.endsWith('.tsx')) {
    let content = fs.readFileSync(filePath, 'utf8');
    let original = content;
    
    // Replace API URL
    content = content.replace(/'http:\/\/localhost:8080\/api/g, '`${import.meta.env.VITE_API_URL || "http://localhost:8080/api"}` + `');
    content = content.replace(/`http:\/\/localhost:8080\/api/g, '`${import.meta.env.VITE_API_URL || "http://localhost:8080/api"}`);
    
    // Replace WebSocket URL
    content = content.replace(/'http:\/\/localhost:8080\/ws/g, '`${import.meta.env.VITE_WS_URL || "http://localhost:8080/ws"}` + `');
    content = content.replace(/`http:\/\/localhost:8080\/ws/g, '`${import.meta.env.VITE_WS_URL || "http://localhost:8080/ws"}`);
    
    if (content !== original) {
      // Fix string concatenation issues generated by above replacements
      content = content.replace(/` \+ ``/g, ''); // Fix empty templates
      fs.writeFileSync(filePath, content, 'utf8');
      console.log(`Updated ${filePath}`);
    }
  }
});
